package com.example.distritos;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;

public class MainActivity extends AppCompatActivity {

    private String[] distritos = {
            "La Chorrera",
            "Arraiján",
            "San Carlos",
            "Capira",
            "Chame",
            "Panamá",
            "San Miguelito",
            "Chepo",
            "Taboga",
            "Bocas del Toro",
            "Changuinola",
            "Alanje",
            "Barú",
            "Boquete",
            "Boquerón",
            "Bugaba",
            "David",
            "Dolega",
            "Gualaca",
            "Remedios",
            "Renacimiento",
            "San Félix",
            "San Lorenzo",
            "Tolé",
            "La Palma",
            "Las Lajas",
            "Besikó",
            "Kusapín",
            "Mironó",
            "Nole Duima",
            "Ñurum",
            "Rio Oeste",
            "Santa Fe",
            "Santa Marta",
            "Bastimentos",
            "Chiriquí Grande",
            "Tierras Altas",
            "San Isidro",
            "Calobre",
            "Chalán",
            "Las Minas",
            "Montijo",
            "Río de Jesús",
            "Santa María",
            "Santiago",
            "Atalaya",
            "La Mesa",
            "Las Palmas",
            "Mariato",
            "Montijo",
            "Río de Jesús",
            "San Francisco",
            "Santa María",
            "Santiago",
            "Cañazas",
            "La Pintada",
            "Natá",
            "Olá",
            "Antón",
            "Chiguirí Arriba",
            "El Chirú",
            "El Retiro",
            "El Valle",
            "Juan Díaz",
            "Ancón",
            "Betania",
            "Bella Vista",
            "Calidonia",
            "Curundú",
            "Pacora",
            "Pueblo Nuevo",
            "Río Abajo",
            "San Felipe",
            "Santa Ana",
            "Tocumen",
            "Belisario Frías",
            "Emberá",
            "Pedro González",
            "Guna Yala",
            "Cémaco",
            "Kuna de Madugandí",
            "Kuna de Wargandí",
            "Mortí",
            "Santa Fe",
            "Jesús",
            "La Peña",
            "El Prado",
            "Limones",
            "Nombre de Dios",
            "Palmas Bellas",
            "Playa Grande",
            "Tubualá",
            "Ailigandí",
            "Puerto Obaldía",
            "Bisira",
            "Muna",
            "Chimán",
            "Miguel de La Borda",
            "Agua Fría",
            "La Encantada",
            "San Francisco",
            "Coclé del Norte",
            "El Cristo",
            "El Palmar",
            "El Picacho",
            "El Rincón",
            "El Roble",
            "Hato Corotú",
            "Las Huacas",
            "Llano Grande",
            "Los Cerritos",
            "Los Cerros de Petaquilla",
            "Río Grande",
            "San Juan",
            "Santo Domingo",
            "Toabré",
            "Torio",
            "Tronosa",
            "Tulú",
            "Quebrada Bonita",
            "San José",
            "Urracá",
            "San Antonio",
            "San Pablo",
            "Cémaco",
            "Hato Chamí",
            "Jungurudó",
            "Río Indio",
            "Sambú",
            "Santa Catalina",
            "Cuango",
            "Llano Tugrí",
            "Bahía Azul",
            "Boca de Cupe",
            "Jaque",
            "Puerto Piña",
            "Río Congo",
            "Río Iglesias",
            "Río Sábalo",
            "Manuel E. Amador",
            "Vásquez",
            "San Francisco",
            "Las Margaritas",
            "Los Ángeles",
            "Palmira",
            "San Juan",
            "San Martín",
            "El Marañón",
            "Guararé",
            "La Enea",
            "La Villa de Los Santos",
            "Los Olivos",
            "San José",
            "Alanje",
            "Cañas Gordas",
            "Divalá",
            "El Tejar",
            "Guarumal",
            "Progreso",
            "Querévalo",
            "Santana",
            "Santo Domingo",
            "Sortová",
            "Las Lomas",
            "Cerro Punta",
            "Guadalupe",
            "Río Sereno",
            "Volcán",
            "Bisira",
            "Chumaguita",
            "Ponuga",
            "Quitapenas",
            "Río Sereno",
            "Lajamina",
            "La Miel",
            "San Andrés",
            "Santa Cruz",
            "Los Pozos",
            "Llano Marín",
            "El Cacao",
            "El Cristo",
            "El Palmar",
            "El Piro",
            "Llano de Catival",
            "Quebrada de Oro",
            "Tijeras",
            "Torno Largo",
            "El Copé",
            "El Palmar",
            "El Picacho",
            "El Rincón",
            "Llano de Catival",
            "San Juan",
            "Santo Domingo",
            "Toabré",
            "Torio",
            "Tronosa",
            "Tulú",
            "Quebrada Bonita",
            "El Cristo",
            "San José",
            "San Pablo",
            "El Copé",
            "Cerro Punta",
            "Guadalupe",
            "Río Sereno",
            "Volcán"
};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        AutoCompleteTextView autoCompleteTextView = findViewById(R.id.autoCompleteTextView);

        ArrayAdapter<String> adapter = new ArrayAdapter<>(this,
                android.R.layout.simple_dropdown_item_1line, distritos);

        autoCompleteTextView.setAdapter(adapter);


    }
}